"""Add plant_nickname to UserPlant

Revision ID: 8ac345f3e176
Revises: c593b6900a3b
Create Date: 2024-09-28 14:55:59.863334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac345f3e176'
down_revision = 'c593b6900a3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userplant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plant_nickname', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userplant', schema=None) as batch_op:
        batch_op.drop_column('plant_nickname')

    # ### end Alembic commands ###
