"""Initial migration.

Revision ID: c593b6900a3b
Revises: 
Create Date: 2024-09-28 14:30:40.094798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c593b6900a3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant',
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('botanical_name', sa.Text(), nullable=True),
    sa.Column('common_name', sa.Text(), nullable=True),
    sa.Column('plant_type', sa.Text(), nullable=True),
    sa.Column('water_needs', sa.Text(), nullable=True),
    sa.Column('min_water_consumption', sa.Integer(), nullable=True),
    sa.Column('max_water_consumption', sa.Integer(), nullable=True),
    sa.Column('climate_zones', sa.Text(), nullable=True),
    sa.Column('light_needs', sa.Text(), nullable=True),
    sa.Column('soil_type', sa.Text(), nullable=True),
    sa.Column('maintenance', sa.Text(), nullable=True),
    sa.Column('flower_color', sa.Text(), nullable=True),
    sa.Column('foliage_color', sa.Text(), nullable=True),
    sa.Column('perfume', sa.Text(), nullable=True),
    sa.Column('aromatic', sa.Text(), nullable=True),
    sa.Column('edible', sa.Text(), nullable=True),
    sa.Column('bore_water_tolerance', sa.Text(), nullable=True),
    sa.Column('frost_tolerance', sa.Text(), nullable=True),
    sa.Column('image_location', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('plant_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('avatar', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('user_description', sa.Text(), nullable=True),
    sa.Column('last_time_seen', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('userplant',
    sa.Column('user_plant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('plant_id', sa.Integer(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('sun_exposure', sa.Text(), nullable=True),
    sa.Column('last_watered', sa.DateTime(), nullable=True),
    sa.Column('pot_diameter', sa.Float(), nullable=True),
    sa.Column('watered_amount', sa.Float(), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('plant_position', sa.Text(), nullable=True),
    sa.Column('registered_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plant.plant_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_plant_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userplant')
    op.drop_table('user')
    op.drop_table('plant')
    # ### end Alembic commands ###
